# Generated by Django 6.1 on 2026-08-11 10:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('api_key', models.CharField(db_index=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('department', models.CharField(default='General', max_length=100)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('embedding', models.TextField(default='[]', help_text='JSON serialized 128 float array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('emp_id', models.CharField(db_index=True, max_length=50)),
                ('emp_name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('device_id', models.CharField(db_index=True, default='default_kiosk', max_length=100)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['emp_id', 'timestamp'], name='attendance__emp_id_39d703_idx'), models.Index(fields=['date', 'emp_id'], name='attendance__date_ef3b47_idx'), models.Index(fields=['uuid'], name='attendance__uuid_2de4b9_idx')],
            },
        ),
    ]
